name: validate
on:
  workflow_run:
    workflows:
      - add codex-reviewed

jobs:
  test:
#    if: ${{ github.event.label.name == 'validate' }}
    runs-on: ubuntu-latest
    steps:
      - name: validate
        uses: actions/github-script@v7
        with:
          script: |
            if (true) {
              core.setFailed('This is a bug');
            }