name: validate

on:
  workflow_run:
    workflows: ['add codex-reviewed']
    types: [completed]

jobs:
  test:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJson(github.event.workflow_run) }}'
      - uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('This is a bug');